parameters:
#    btc_trip_backoffice.example.class: BtcTrip\BackofficeBundle\Example

services:
#    btc_trip_backoffice.example:
#        class: %btc_trip_backoffice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
