imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        assets_version: 3.0.0
        assets_version_format: v%%2$s/%%1$s
        # "%%s?v=%%s"
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['BtcTripBackofficeBundle', 'BtcTripHotelsBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
#    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
#    spool:     { type: memory }
    
    
doctrine_mongodb:
    connections:
        default:
            server: %database_server%
            options: {}
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true
    default_commit_options: ~

