imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        event_all:
            bubble: false
            action_level: DEBUG
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%_event_all.log
            channels: event    
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
        varios:
            type:  stream
            path:  %kernel.logs_dir%/debug.log
            level: debug

assetic:
    use_controller: true
    bundles: ['BtcTripBackofficeBundle', 'BtcTripHotelsBundle']

#swiftmailer:
#    delivery_address: me@example.com
