
#btc_trip_search_homepage:
#    pattern:  /results
#    defaults: { _controller: BtcTripSearchBundle:Search:results }

btc_trip_search:
    type:  annotation
    resource: "@BtcTripSearchBundle/Controller/SearchController.php"

btc_trip_autocomplete:
    type:  annotation
    resource: "@BtcTripSearchBundle/Controller/AutocompleteController.php"

btc_trip_checkout:
    type:  annotation
    resource: "@BtcTripSearchBundle/Controller/CheckoutController.php"
   
btc_trip_payment_handler:
    type:  annotation
    resource: "@BtcTripSearchBundle/Controller/PaymentHandlerController.php"
 
#btc_trip_advertising:
#    type:  annotation
#    resource: "@BtcTripSearchBundle/Controller/AdvertisingController.php"

btc_trip_about_us:
    path: /about_us
    defaults:
        _controller: FrameworkBundle:Template:template
        template: "BtcTripSearchBundle:StaticPages:about_us.html.php"

 